/**
 * Codegen: openapi/regos_api_swagger.json -> committed generated node data.
 *
 * Emits, per action node:
 *   nodes/<Node>/generated/metadata.ts    resource.operation -> { path, envelope, paginated, fields }
 *   nodes/<Node>/generated/properties.ts  INodeProperties[] (resource/operation selectors + field collections)
 * and for the trigger:
 *   nodes/RegosTrigger/generated/events.ts
 *
 * Modes:
 *   (default)  write files
 *   --check    regenerate in memory and fail if committed output differs
 *   --diff     print which files would change
 *
 * Deterministic by construction: sorted iteration, no timestamps, no randomness.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

type JsonSchema = {
	$ref?: string;
	type?: string | string[];
	format?: string;
	enum?: string[];
	items?: JsonSchema;
	properties?: Record<string, JsonSchema>;
	oneOf?: JsonSchema[];
};

interface OpenApiSpec {
	paths: Record<string, { post: { tags?: string[]; requestBody?: { content: Record<string, { schema: JsonSchema }> }; responses: Record<string, { content?: Record<string, { schema: JsonSchema }> }> } }>;
	components: { schemas: Record<string, JsonSchema> };
}

type FieldKind =
	| 'string'
	| 'number'
	| 'boolean'
	| 'triBoolean'
	| 'dateTime'
	| 'options'
	| 'idList'
	| 'stringList'
	| 'filters'
	| 'json';

interface FieldModel {
	api: string;
	param: string;
	kind: FieldKind;
	required: boolean;
	enumValues?: string[];
}

interface OperationModel {
	resource: string; // tag
	value: string; // n8n operation value
	display: string;
	description: string;
	path: string; // literal swagger path without leading slash
	envelope: 'offsettedArray' | 'array' | 'object' | 'insert' | 'raw';
	paginated: boolean;
	fields: FieldModel[];
}

interface DomainsConfig {
	excluded: string[];
	nodes: Record<string, string[]>;
}

interface OverridePatch {
	/** Replaces the operation's display name in the Operation dropdown. */
	displayName?: string;
	/** Replaces the generated operation description (the sub-text under the name). */
	description?: string;
	/** API field names to force as required top-level parameters. */
	required?: string[];
}

// This file is an ES module (.mts) so that n8n's stock ESLint config, which scopes its
// rules to **/*.ts, leaves dev-time tooling alone. That means no __dirname/require.
const HERE = dirname(fileURLToPath(import.meta.url));

const ROOT = resolve(HERE, '..', '..');
const SPEC_PATH = join(ROOT, 'openapi', 'regos_api_swagger.json');
const DOMAINS_PATH = join(HERE, 'domains.json');
const OVERRIDES_DIR = join(HERE, 'overrides');

const NODE_DIRS: Record<string, string> = {
	Regos: 'nodes/Regos/generated',
	RegosDocuments: 'nodes/RegosDocuments/generated',
	RegosPos: 'nodes/RegosPos/generated',
	RegosCrm: 'nodes/RegosCrm/generated',
	RegosReports: 'nodes/RegosReports/generated',
};

const GENERATED_HEADER =
	'// AUTO-GENERATED by scripts/generate — DO NOT EDIT. Run: npm run generate\n';

// n8n lint (node-param-resource-with-plural-option) rejects resource names its
// pluralize heuristic considers plural; map those to compliant display names.
const RESOURCE_DISPLAY_FIXES: Record<string, string> = {
	Sys: 'System',
	DocAdditionalExpenses: 'Doc Additional Expense',
};

// Operation actions that the sentence-case lint heuristic cannot derive mechanically.
const ACTION_FIXES: Record<string, string> = {
	'PosDocSession.xReport': 'Print x report',
};

function resourceDisplay(tag: string): string {
	return RESOURCE_DISPLAY_FIXES[tag] ?? titleCase(tag);
}

const ACRONYMS: Record<string, string> = {
	Id: 'ID',
	Ids: 'IDs',
	Uuid: 'UUID',
	Uuids: 'UUIDs',
	Url: 'URL',
	Api: 'API',
	Sms: 'SMS',
	Vat: 'VAT',
	Pos: 'POS',
	Crm: 'CRM',
	Tin: 'TIN',
	Sla: 'SLA',
	Edm: 'EDM',
	Icps: 'ICPS',
	Kdt: 'KDT',
};

function words(identifier: string): string[] {
	return identifier
		.replace(/[_\s]+/g, ' ')
		.replace(/([a-z0-9])([A-Z])/g, '$1 $2')
		.replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
		.trim()
		.split(' ')
		.filter((w) => w !== '');
}

function titleCase(identifier: string): string {
	return words(identifier)
		.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
		.map((w) => ACRONYMS[w] ?? w)
		.join(' ');
}

function lowerFirst(value: string): string {
	return value.charAt(0).toLowerCase() + value.slice(1);
}

const ACRONYM_VALUES = new Set(Object.values(ACRONYMS));

/** "Zero Quantity" -> "zero quantity", but "Item VAT" -> "item VAT". */
function sentenceCase(identifier: string): string {
	return titleCase(identifier)
		.split(' ')
		.map((w) => (ACRONYM_VALUES.has(w) ? w : w.toLowerCase()))
		.join(' ');
}

function capitalizeFirst(value: string): string {
	return value.charAt(0).toUpperCase() + value.slice(1);
}

// Words whose article does not follow the bare vowel rule ("a user", not "an user").
const CONSONANT_SOUND = /^(user|unit|uuid|url|uz)\b/i;

/** "account" -> "an account", "user" -> "a user". */
function withArticle(noun: string): string {
	const vowelSound = /^[aeiou]/i.test(noun) && !CONSONANT_SOUND.test(noun);
	return `${vowelSound ? 'an' : 'a'} ${noun}`;
}

// REGOS verbs whose generated wording would otherwise be unreadable. Each entry
// builds the whole sentence, because the article placement differs per phrasing.
const VERB_PHRASES: Record<string, (resource: string) => string> = {
	storno: (r) => `Reverse an operation on ${withArticle(r)}`,
	getcurrent: (r) => `Get the currently open ${r}`,
	getCurrent: (r) => `Get the currently open ${r}`,
	isCanDo: (r) => `Check whether the action is allowed for ${withArticle(r)}`,
	deleteMark: (r) => `Mark ${withArticle(r)} for deletion`,
	performCancel: (r) => `Cancel the posting of ${withArticle(r)}`,
	xReport: (r) => `Print an X report for ${withArticle(r)}`,
	zReport: (r) => `Print a Z report for ${withArticle(r)}`,
	posGet: (r) => `Retrieve ${r} data from the POS`,
};

/**
 * Human-readable operation description. The swagger carries no summaries or
 * descriptions at all, so every sentence here is derived from the resource name
 * and the operation verb. `scripts/generate/overrides/` can replace any of them.
 */
function describeOperation(
	tag: string,
	value: string,
	display: string,
	paginated: boolean,
	hasRequiredId: boolean,
): string {
	const resource = sentenceCase(resourceDisplay(tag));
	const parts = words(display);
	const verb = lowerFirst(parts[0] ?? '');
	const rest = sentenceCase(parts.slice(1).join(' '));

	if (verb === 'get' && !rest) {
		if (paginated) return `Retrieve many ${resource} records`;
		return hasRequiredId ? `Retrieve ${withArticle(resource)} by ID` : `Retrieve ${resource} data`;
	}
	if (verb === 'add' && !rest) return `Create ${withArticle(resource)}`;
	if (verb === 'edit' && !rest) return `Update ${withArticle(resource)}`;
	if (verb === 'delete' && !rest) return `Delete ${withArticle(resource)}`;
	if (value === 'perform') return `Post ${withArticle(resource)}`;

	const phrase = VERB_PHRASES[value];
	if (phrase) return phrase(resource);

	// A bare verb reads as an action on the record ("Close a deal"); a verb with a
	// qualifier reads as an action on part of it ("Add participant for a chat").
	if (!rest) return capitalizeFirst(`${verb} ${withArticle(resource)}`);
	return capitalizeFirst(`${verb} ${rest} for ${withArticle(resource)}`);
}

// Boolean flags whose meaning the generic template cannot express. Anything not
// listed falls back to "Whether <field> is enabled" with is_/_enabled stripped.
const BOOLEAN_DESCRIPTIONS: Record<string, string> = {
	access_all: 'Whether access is granted to all records',
	blocked: 'Whether the record is blocked',
	booked: 'Whether stock is reserved by this document',
	closed: 'Whether the record is closed',
	compress_data: 'Whether to compress the response payload',
	deleted_mark: 'Whether the record is marked for deletion',
	exclude: 'Whether to exclude the listed records instead of including them',
	exclude_storno: 'Whether to exclude reversed operations',
	finished: 'Whether the record is finished',
	forced: 'Whether to force the operation, ignoring soft checks',
	has_child: 'Whether the record has child records',
	has_image: 'Whether the record has an image',
	hidden: 'Whether the record is hidden',
	in_base_currency: 'Whether amounts are expressed in the base currency',
	include: 'Whether to include the listed records',
	include_data: 'Whether to include the related data in the response',
	include_mentions: 'Whether to include mentions',
	include_name: 'Whether to include names in the response',
	include_schedule: 'Whether to include schedule information',
	include_staff_private: 'Whether to include private staff information',
	is_return: 'Whether this is a return',
	muted: 'Whether notifications are muted',
	only_deviation: 'Whether to return only records that deviate',
	performed: 'Whether the document is posted',
	pinned: 'Whether the record is pinned',
	positive: 'Whether only positive values are returned',
	rating_enabled: 'Whether rating is enabled',
	replace_mode: 'Whether existing values are replaced instead of merged',
	required: 'Whether the field is mandatory',
	run_immediately: 'Whether to run the task immediately',
	save: 'Whether to persist the result',
	unlimited: 'Whether the value is unlimited',
	update_actual_quantity: 'Whether to update the actual quantity',
	value: 'Whether the flag is set',
	virtual: 'Whether the record is virtual',
	zero_price: 'Whether records with a zero price are included',
	zero_quantity: 'Whether records with a zero quantity are included',
};

function booleanDescription(api: string): string {
	const known = BOOLEAN_DESCRIPTIONS[api];
	if (known) return known;
	// "is_default" / "auto_close_enabled" -> "default" / "auto close"
	const stripped = api.replace(/^is_/, '').replace(/_enabled$/, '');
	return `Whether ${sentenceCase(stripped)} is enabled`;
}

/**
 * A scalar `id`/`uuid` on a non-list endpoint identifies the record being acted
 * on, so it is surfaced as a required top-level parameter instead of hiding in
 * Additional Fields. Array filters (`ids`) stay optional — they narrow a list.
 *
 * Reads that return a list are excluded: there the `id`/`uuid` is one more filter,
 * and requiring it makes the search unusable (REGOS marks nothing as required in
 * the swagger, so the shape of the response is the only reliable signal). Both
 * halves of the test are load-bearing: `pos/DocCheque/AddRetailCard` also returns
 * an Array-shaped envelope but genuinely needs its key, and `Tag/Get` is a list
 * read whose only sibling field is `include_data`. Endpoints that need the key
 * back can opt in via `required` in scripts/generate/overrides.
 */
function isPrimaryKeyField(
	field: FieldModel,
	paginated: boolean,
	responseName: string,
	value: string,
): boolean {
	if (paginated) return false;
	if (/Array/.test(responseName) && /^get/i.test(value)) return false;
	if (field.api !== 'id' && field.api !== 'uuid') return false;
	return field.kind === 'number' || field.kind === 'string';
}

function camelCase(segments: string[]): string {
	const joined = segments.map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
	return lowerFirst(joined);
}

function loadSpec(): OpenApiSpec {
	return JSON.parse(readFileSync(SPEC_PATH, 'utf-8')) as OpenApiSpec;
}

function loadDomains(): DomainsConfig {
	return JSON.parse(readFileSync(DOMAINS_PATH, 'utf-8')) as DomainsConfig;
}

function loadOverrides(): Record<string, OverridePatch> {
	const overrides: Record<string, OverridePatch> = {};
	if (!existsSync(OVERRIDES_DIR)) return overrides;
	for (const file of readdirSync(OVERRIDES_DIR).sort()) {
		if (!file.endsWith('.json')) continue;
		const content = JSON.parse(readFileSync(join(OVERRIDES_DIR, file), 'utf-8')) as Record<string, OverridePatch>;
		for (const [key, patch] of Object.entries(content)) {
			overrides[key] = { ...overrides[key], ...patch };
		}
	}
	return overrides;
}

function resolveRef(spec: OpenApiSpec, schema: JsonSchema | undefined): { name?: string; schema: JsonSchema } {
	if (schema?.$ref) {
		const name = schema.$ref.replace('#/components/schemas/', '');
		const resolved = spec.components.schemas[name];
		if (!resolved) throw new Error(`Unresolvable $ref: ${schema.$ref}`);
		return { name, schema: resolved };
	}
	return { schema: schema ?? {} };
}

function typeOf(schema: JsonSchema): { type: string; nullable: boolean } {
	const raw = schema.type;
	if (Array.isArray(raw)) {
		const nonNull = raw.filter((t) => t !== 'null');
		return { type: nonNull[0] ?? 'object', nullable: raw.includes('null') };
	}
	return { type: raw ?? 'object', nullable: false };
}

function isDateField(name: string, type: string): boolean {
	return (type === 'integer' || type === 'number') && /(^|_)date($|_)|_at$/.test(name);
}

function classifyField(spec: OpenApiSpec, apiName: string, rawSchema: JsonSchema): FieldModel {
	const { name: refName, schema } = resolveRef(spec, rawSchema);
	const { type, nullable } = typeOf(schema);

	let kind: FieldKind;
	let enumValues: string[] | undefined;

	if (schema.enum && type === 'string') {
		kind = 'options';
		enumValues = [...schema.enum].sort();
	} else if (type === 'array') {
		const item = resolveRef(spec, schema.items);
		const itemType = typeOf(item.schema).type;
		if (item.name === 'Filter') kind = 'filters';
		else if (itemType === 'integer' || itemType === 'number') kind = 'idList';
		else if (itemType === 'string' && !item.schema.enum) kind = 'stringList';
		else kind = 'json';
	} else if (type === 'boolean') {
		kind = nullable ? 'triBoolean' : 'boolean';
	} else if (type === 'integer' || type === 'number') {
		kind = isDateField(apiName, type) ? 'dateTime' : 'number';
	} else if (type === 'string') {
		kind = 'string';
	} else {
		kind = 'json';
	}

	void refName;
	return { api: apiName, param: apiName, kind, required: false, enumValues };
}

/** Name of the success (non-ErrorResult) 200 response schema, e.g. "ChequeArrayRegosObjectResult". */
function responseSchemaName(responseSchema: JsonSchema | undefined): string {
	const refs = (responseSchema?.oneOf ?? [responseSchema ?? {}])
		.map((s) => s?.$ref ?? '')
		.filter((r) => r !== '' && !r.endsWith('/ErrorResult'));
	return refs[0]?.replace('#/components/schemas/', '') ?? '';
}

function envelopeOf(responseSchema: JsonSchema | undefined): OperationModel['envelope'] {
	const name = responseSchemaName(responseSchema);
	if (name.endsWith('RegosOffsettedArrayResult')) return 'offsettedArray';
	if (name.endsWith('RegosArrayResult')) return 'array';
	if (name.endsWith('RegosObjectResult')) return 'object';
	if (name === 'InsertResult') return 'insert';
	return 'raw';
}

function buildModel(spec: OpenApiSpec, domains: DomainsConfig): Map<string, OperationModel[]> {
	const tagToNode = new Map<string, string>();
	for (const [node, tags] of Object.entries(domains.nodes)) {
		for (const tag of tags) tagToNode.set(tag, node);
	}
	const excluded = new Set(domains.excluded);

	const byNode = new Map<string, OperationModel[]>();
	const unmappedTags = new Set<string>();
	const seen = new Map<string, string>(); // `${tag}.${value}` -> path (collision check)

	for (const [path, item] of Object.entries(spec.paths).sort(([a], [b]) => a.localeCompare(b))) {
		const tag = item.post.tags?.[0];
		if (!tag) throw new Error(`Path without tag: ${path}`);
		if (excluded.has(tag)) continue;

		const node = tagToNode.get(tag);
		if (!node) {
			unmappedTags.add(tag);
			continue;
		}

		const segments = path.replace(/^\//, '').split('/');
		const isPos = segments[0] === 'pos';
		const rootLength = isPos ? 2 : 1;
		let remainder = segments.slice(rootLength);
		if (remainder.length === 0) throw new Error(`Cannot derive operation name from path: ${path}`);

		// Some tags span both /X/Get and /pos/X/get; disambiguate the POS variant.
		let value = camelCase(remainder);
		if (seen.has(`${tag}.${value}`) && isPos) {
			remainder = ['pos', ...remainder];
			value = camelCase(remainder);
		}

		const collisionKey = `${tag}.${value}`;
		const existing = seen.get(collisionKey);
		if (existing) throw new Error(`Operation collision for ${collisionKey}: ${existing} vs ${path}`);
		seen.set(collisionKey, path);

		const requestSchema = item.post.requestBody?.content?.['application/json']?.schema;
		const { schema: resolved } = resolveRef(spec, requestSchema);
		const responseSchema = item.post.responses?.['200']?.content?.['application/json']?.schema;
		const envelope = envelopeOf(responseSchema);
		const responseName = responseSchemaName(responseSchema);

		const properties = resolved.properties ?? {};
		const paginated =
			envelope === 'offsettedArray' && 'limit' in properties && 'offset' in properties;

		const fields: FieldModel[] = [];
		for (const [apiName, propSchema] of Object.entries(properties).sort(([a], [b]) => a.localeCompare(b))) {
			if (paginated && (apiName === 'limit' || apiName === 'offset')) continue;
			const field = classifyField(spec, apiName, propSchema);
			field.required = isPrimaryKeyField(field, paginated, responseName, value);
			fields.push(field);
		}

		const display = titleCase(remainder.join(' '));
		const model: OperationModel = {
			resource: tag,
			value,
			display,
			description: describeOperation(
				tag,
				value,
				display,
				paginated,
				fields.some((f) => f.required),
			),
			path: path.replace(/^\//, ''),
			envelope,
			paginated,
			fields,
		};

		const list = byNode.get(node) ?? [];
		list.push(model);
		byNode.set(node, list);
	}

	if (unmappedTags.size > 0) {
		throw new Error(
			`Tags not assigned to any node in scripts/generate/domains.json: ${[...unmappedTags].sort().join(', ')}. ` +
				'Assign each new REGOS resource to a node explicitly.',
		);
	}

	return byNode;
}

function applyOverrides(byNode: Map<string, OperationModel[]>, overrides: Record<string, OverridePatch>): void {
	const known = new Set<string>();
	for (const ops of byNode.values()) {
		for (const op of ops) known.add(`${op.resource}.${op.value}`);
	}
	const unknown = Object.keys(overrides).filter((key) => !known.has(key));
	if (unknown.length > 0) {
		throw new Error(
			`Overrides reference unknown operations (swagger drift?): ${unknown.sort().join(', ')}`,
		);
	}
	for (const ops of byNode.values()) {
		for (const op of ops) {
			const patch = overrides[`${op.resource}.${op.value}`];
			if (!patch) continue;
			if (patch.displayName) op.display = patch.displayName;
			if (patch.description) op.description = patch.description;
			if (patch.required) {
				const known = new Set(op.fields.map((f) => f.api));
				const missing = patch.required.filter((name) => !known.has(name));
				if (missing.length > 0) {
					throw new Error(
						`Override ${op.resource}.${op.value} marks unknown fields as required: ${missing.join(', ')}`,
					);
				}
				for (const field of op.fields) {
					if (patch.required.includes(field.api)) field.required = true;
				}
				// The generated sentence depends on whether the operation has a required key,
				// and descriptions are built before overrides run — so rebuild it here unless
				// the patch supplies its own wording.
				if (!patch.description) {
					op.description = describeOperation(
						op.resource,
						op.value,
						op.display,
						op.paginated,
						op.fields.some((f) => f.required),
					);
				}
			}
		}
	}
}

function fieldToProperty(field: FieldModel, show: { resource: string[]; operation: string[] }): object {
	const displayName = titleCase(field.api);
	const base = { displayName, name: field.param };
	void show;

	switch (field.kind) {
		case 'string': {
			const property: Record<string, unknown> = { ...base, type: 'string', default: '' };
			if (/password|secret|token/i.test(field.api)) property.typeOptions = { password: true };
			if (/email/i.test(field.api)) property.placeholder = 'name@email.com';
			return property;
		}
		case 'number':
			if (field.api === 'limit') {
				return {
					...base,
					type: 'number',
					typeOptions: { minValue: 1 },
					default: 50,
					description: 'Max number of results to return',
				};
			}
			// Required keys are real record IDs, so the UI should reject 0 before execution.
			if (field.required) return { ...base, type: 'number', typeOptions: { minValue: 1 }, default: 0 };
			return { ...base, type: 'number', default: 0 };
		case 'boolean':
			return { ...base, type: 'boolean', default: false, description: booleanDescription(field.api) };
		case 'triBoolean':
			return {
				...base,
				type: 'options',
				options: [
					{ name: 'Default', value: 'default' },
					{ name: 'No', value: 'false' },
					{ name: 'Yes', value: 'true' },
				],
				default: 'default',
			};
		case 'dateTime':
			return { ...base, type: 'dateTime', default: '' };
		case 'options': {
			const options = (field.enumValues ?? [])
				.map((v) => ({ name: titleCase(v), value: v }))
				.sort((a, b) => a.name.localeCompare(b.name));
			return { ...base, type: 'options', options, default: options[0]?.value ?? '' };
		}
		case 'idList':
			return { ...base, type: 'string', default: '', placeholder: 'e.g. 1,2,3', description: 'Comma-separated list of IDs' };
		case 'stringList':
			return { ...base, type: 'string', default: '', description: 'Comma-separated list of values' };
		case 'filters':
			return {
				...base,
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				options: [
					{
						name: 'filter',
						displayName: 'Filter',
						values: [
							{ displayName: 'Field', name: 'field', type: 'string', default: '' },
							{
								displayName: 'Operator',
								name: 'operator',
								type: 'options',
								options: [
									'Default',
									'Equal',
									'Exists',
									'Greater',
									'GreaterOrEqual',
									'In',
									'Less',
									'LessOrEqual',
									'Like',
									'NotEqual',
									'NotExists',
									'NotIn',
								].map((v) => ({ name: titleCase(v), value: v })),
								default: 'Default',
							},
							{ displayName: 'Value', name: 'value', type: 'string', default: '' },
						],
					},
				],
			};
		case 'json':
			return { ...base, type: 'json', default: '' };
		default:
			return { ...base, type: 'string', default: '' };
	}
}

interface NodeEmitConfig {
	/** Extra resource options that are hand-written (currently only Batch on the core node). */
	extraResources?: Array<{ name: string; value: string }>;
}

function buildProperties(ops: OperationModel[], config: NodeEmitConfig): object[] {
	const resources = [...new Set(ops.map((op) => op.resource))].sort();

	const resourceOptions = [
		...resources.map((tag) => ({ name: resourceDisplay(tag), value: lowerFirst(tag) })),
		...(config.extraResources ?? []),
	].sort((a, b) => a.name.localeCompare(b.name));

	const properties: object[] = [
		{
			displayName: 'Resource',
			name: 'resource',
			type: 'options',
			noDataExpression: true,
			options: resourceOptions,
			default: resourceOptions[0]?.value ?? '',
		},
	];

	for (const tag of resources) {
		const resourceValue = lowerFirst(tag);
		const resourceOps = ops.filter((op) => op.resource === tag).sort((a, b) => a.display.localeCompare(b.display));

		const operationOptions = resourceOps.map((op) => {
			// Sentence case, but acronyms keep their casing — otherwise the action reads
			// "Add retail card pos doc cheque" under a "POS Doc Cheque" resource label.
			// n8n's isSentenceCase() skips all-caps words, so this stays lint-clean.
			const raw = sentenceCase(`${op.display} ${resourceDisplay(tag)}`);
			const action =
				ACTION_FIXES[`${tag}.${op.value}`] ?? raw.charAt(0).toUpperCase() + raw.slice(1);
			return {
				name: op.display,
				value: op.value,
				action,
					description: op.description,
			};
		});

		// Never default a resource to a destructive operation — a user opening the node
		// should land on a read, or at worst on something that does not delete.
		const isDestructive = (value: string) => /^(delete|remove|cancel|storno)/i.test(value);
		const defaultOp =
			resourceOps.find((op) => op.value === 'get')?.value ??
			resourceOps.find((op) => /^get/i.test(op.value))?.value ??
			resourceOps.find((op) => !isDestructive(op.value))?.value ??
			resourceOps[0]?.value ??
			'';

		properties.push({
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: [resourceValue] } },
			options: operationOptions,
			default: defaultOp,
		});

		for (const op of resourceOps) {
			const show = { resource: [resourceValue], operation: [op.value] };

			if (op.paginated) {
				properties.push(
					{
						displayName: 'Return All',
						name: 'returnAll',
						type: 'boolean',
						default: false,
						description: 'Whether to return all results or only up to a given limit',
						displayOptions: { show },
					},
					{
						displayName: 'Limit',
						name: 'limit',
						type: 'number',
						typeOptions: { minValue: 1 },
						default: 50,
						description: 'Max number of results to return',
						displayOptions: { show: { ...show, returnAll: [false] } },
					},
				);
			}

			// Required fields (the record's primary key) are shown as top-level
			// parameters; everything else stays behind Additional Fields.
			for (const field of op.fields.filter((f) => f.required)) {
				properties.push({
					...(fieldToProperty(field, show) as Record<string, unknown>),
					required: true,
					displayOptions: { show },
				});
			}

			const optionalFields = op.fields.filter((f) => !f.required);
			if (optionalFields.length > 0) {
				const options = optionalFields
					.map((field) => fieldToProperty(field, show))
					.sort((a, b) => (a as { displayName: string }).displayName.localeCompare((b as { displayName: string }).displayName));

				properties.push({
					displayName: 'Additional Fields',
					name: 'additionalFields',
					type: 'collection',
					placeholder: 'Add Field',
					default: {},
					displayOptions: { show },
					options,
				});
			}
		}
	}

	return properties;
}

function buildMetadata(ops: OperationModel[]): Record<string, Record<string, object>> {
	const meta: Record<string, Record<string, object>> = {};
	for (const op of [...ops].sort((a, b) => a.resource.localeCompare(b.resource) || a.value.localeCompare(b.value))) {
		const resourceValue = lowerFirst(op.resource);
		meta[resourceValue] = meta[resourceValue] ?? {};
		meta[resourceValue][op.value] = {
			path: op.path,
			envelope: op.envelope,
			paginated: op.paginated,
			fields: op.fields.map((f) => ({ api: f.api, param: f.param, kind: f.kind, required: f.required })),
		};
	}
	return meta;
}

function buildEvents(
	spec: OpenApiSpec,
	domains: DomainsConfig,
): { options: object[]; resolveMap: Record<string, string> } {
	const enumSchema = spec.components.schemas.WebHookActionsEnum;
	if (!enumSchema?.enum) throw new Error('WebHookActionsEnum not found in swagger');

	const allTags = Object.values(domains.nodes).flat().sort((a, b) => b.length - a.length);

	// An event is resolvable when its entity tag has a <Tag>/Get endpoint whose request accepts ids[].
	const resolvableTags = new Set<string>();
	for (const tag of allTags) {
		const getPath = spec.paths[`/${tag}/Get`];
		if (!getPath) continue;
		const requestSchema = getPath.post.requestBody?.content?.['application/json']?.schema;
		const { schema } = resolveRef(spec, requestSchema);
		if (schema.properties && 'ids' in schema.properties) resolvableTags.add(tag);
	}

	const options: object[] = [];
	const resolveMap: Record<string, string> = {};

	for (const event of [...enumSchema.enum].filter((e) => e !== 'Default').sort()) {
		const group = allTags.find((tag) => event.startsWith(tag));
		options.push({
			// `value` stays the exact REGOS enum — it is what incoming payloads are matched
			// against. Only the label is humanized.
			name: titleCase(event),
			value: event,
			description: group
				? `${titleCase(group)} event (REGOS action "${event}")`
				: `REGOS event "${event}"`,
		});
		if (group && resolvableTags.has(group)) resolveMap[event] = `${group}/Get`;
	}

	// n8n sorts multiOptions by label, so sort by the humanized name rather than the
	// raw enum value the labels were derived from.
	options.sort((a, b) => (a as { name: string }).name.localeCompare((b as { name: string }).name));

	return { options, resolveMap };
}

async function formatTs(content: string): Promise<string> {
	return await prettier.format(content, {
		parser: 'typescript',
		useTabs: true,
		singleQuote: true,
		printWidth: 100,
		trailingComma: 'all',
	});
}

async function generateOutputs(): Promise<Map<string, string>> {
	const spec = loadSpec();
	const domains = loadDomains();
	const overrides = loadOverrides();
	const byNode = buildModel(spec, domains);
	applyOverrides(byNode, overrides);

	const outputs = new Map<string, string>();

	for (const [node, dir] of Object.entries(NODE_DIRS)) {
		const ops = byNode.get(node) ?? [];
		if (ops.length === 0) throw new Error(`No operations mapped to node ${node}`);

		const config: NodeEmitConfig =
			node === 'Regos' ? { extraResources: [{ name: 'Batch', value: 'batch' }] } : {};

		const properties = buildProperties(ops, config);
		const metadata = buildMetadata(ops);

		outputs.set(
			`${dir}/properties.ts`,
			await formatTs(
				`${GENERATED_HEADER}import type { INodeProperties } from 'n8n-workflow';\n\n` +
					`export const nodeProperties: INodeProperties[] = ${JSON.stringify(properties, null, '\t')};\n`,
			),
		);
		outputs.set(
			`${dir}/metadata.ts`,
			await formatTs(
				`${GENERATED_HEADER}import type { NodeOperationsMeta } from '../../shared/types';\n\n` +
					`export const operationsMeta = ${JSON.stringify(metadata, null, '\t')} as unknown as NodeOperationsMeta;\n`,
			),
		);
	}

	const events = buildEvents(loadSpec(), domains);
	outputs.set(
		'nodes/RegosTrigger/generated/events.ts',
		await formatTs(
			`${GENERATED_HEADER}import type { INodePropertyOptions } from 'n8n-workflow';\n\n` +
				`export const webhookEvents = ${JSON.stringify(events.options, null, '\t')} as INodePropertyOptions[];\n\n` +
				`/** Event -> "<Tag>/Get" endpoint used by the Resolve Data option (events whose payload id can be expanded). */\n` +
				`export const eventResolveMap: Record<string, string> = ${JSON.stringify(events.resolveMap, null, '\t')};\n`,
		),
	);

	return outputs;
}

async function main(): Promise<void> {
	const mode = process.argv.includes('--check') ? 'check' : process.argv.includes('--diff') ? 'diff' : 'write';
	const outputs = await generateOutputs();

	if (mode === 'write') {
		for (const [relPath, content] of outputs) {
			const target = join(ROOT, relPath);
			mkdirSync(dirname(target), { recursive: true });
			writeFileSync(target, content, 'utf-8');
		}
		let totalOps = 0;
		for (const [relPath] of outputs) if (relPath.endsWith('metadata.ts')) totalOps++;
		console.log(`Generated ${outputs.size} files (${totalOps} action nodes + trigger events).`);
		return;
	}

	const changed: string[] = [];
	for (const [relPath, content] of outputs) {
		const target = join(ROOT, relPath);
		const current = existsSync(target) ? readFileSync(target, 'utf-8') : '<missing>';
		if (current !== content) changed.push(relPath);
	}

	if (mode === 'diff') {
		if (changed.length === 0) console.log('Generated output is up to date.');
		else {
			console.log('Files that would change:');
			for (const file of changed) console.log(`  ${file}`);
		}
		return;
	}

	// check
	if (changed.length > 0) {
		console.error('Committed generated output does not match the swagger. Run: npm run generate');
		for (const file of changed) console.error(`  out of date: ${file}`);
		process.exit(1);
	}
	console.log('Generated output matches the swagger.');
}

/* Exported for tests (scripts/generate is dev-time only). */
export {
	buildModel,
	buildEvents,
	loadSpec,
	loadDomains,
	loadOverrides,
	applyOverrides,
	generateOutputs,
	titleCase,
};
export type { OperationModel };

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
	void main().catch((error) => {
		console.error(error instanceof Error ? error.message : error);
		process.exit(1);
	});
}
